/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   keycode_mac.h                                      :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: calamber <calamber@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2019/07/15 17:44:28 by calamber          #+#    #+#             */
/*   Updated: 2019/12/13 01:42:50 by calamber         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef KEYCODE_MAC_H
# define KEYCODE_MAC_H

# define KEY_ESCAPE (unsigned long)(27)
# define KEY_F1  (unsigned long)(122)
# define KEY_F2 (unsigned long)(120)
# define KEY_F3 (unsigned long)(99)
# define KEY_F4 (unsigned long)(118)
# define KEY_F5 (unsigned long)(96)
# define KEY_F6 (unsigned long)(97)
# define KEY_F7 (unsigned long)(98)
# define KEY_F8 (unsigned long)(100)
# define KEY_F9 (unsigned long)(101)
# define KEY_F10 (unsigned long)(109)
# define KEY_F11 (unsigned long)(103)
# define KEY_F12 (unsigned long)(111)
# define KEY_F13 (unsigned long)(105)
# define KEY_F14 (unsigned long)(107)
# define KEY_F15 (unsigned long)(113)
# define KEY_F16 (unsigned long)(106)
# define KEY_F17 (unsigned long)(64)
# define KEY_F18 (unsigned long)(79)
# define KEY_F19 (unsigned long)(80)
# define KEY_TILDE (unsigned long)(50)
# define KEY_1 (unsigned long)(18)
# define KEY_2 (unsigned long)(19)
# define KEY_3 (unsigned long)(20)
# define KEY_4 (unsigned long)(21)
# define KEY_5 (unsigned long)(23)
# define KEY_6 (unsigned long)(22)
# define KEY_7 (unsigned long)(26)
# define KEY_8 (unsigned long)(28)
# define KEY_9 (unsigned long)(25)
# define KEY_0 (unsigned long)(29)
# define KEY_MINUS (unsigned long)(27)
# define KEY_EQUAL (unsigned long)(24)
# define KEY_BACKSPACE (unsigned long)(51)
# define KEY_TAB (unsigned long)(0x09)
# define KEY_Q (unsigned long)(12)
# define KEY_W (unsigned long)(13)
# define KEY_E (unsigned long)(14)
# define KEY_R (unsigned long)(15)
# define KEY_T (unsigned long)(17)
# define KEY_Y (unsigned long)(16)
# define KEY_U (unsigned long)(32)
# define KEY_I (unsigned long)(34)
# define KEY_O (unsigned long)(31)
# define KEY_P (unsigned long)(35)
# define KEY_OPEN_BRACKET (unsigned long)(33)
# define KEY_OPEN_BRACE (unsigned long)(33)
# define KEY_CLOSE_BRACKET (unsigned long)(30)
# define KEY_CLOSE_BRACE (unsigned long)(30)
# define KEY_BACKSLASH (unsigned long)(42)
# define KEY_PIPE (unsigned long)(42)
# define KEY_CAPSLOCK (unsigned long)(272)
# define KEY_A (unsigned long)(0)
# define KEY_S (unsigned long)(1)
# define KEY_D (unsigned long)(2)
# define KEY_F (unsigned long)(3)
# define KEY_G (unsigned long)(5)
# define KEY_H (unsigned long)(4)
# define KEY_J (unsigned long)(38)
# define KEY_K (unsigned long)(40)
# define KEY_L (unsigned long)(37)
# define KEY_COLON (unsigned long)(41)
# define KEY_SEMI_COLON (unsigned long)(41)
# define KEY_SIMPLE_QUOTE (unsigned long)(39)
# define KEY_DOUBLE_QUOTES (unsigned long)(39)
# define KEY_ENTER (unsigned long)(0xA)
# define KEY_SHIFT_LEFT (unsigned long)(257)
# define KEY_Z (unsigned long)(6)
# define KEY_X (unsigned long)(7)
# define KEY_C (unsigned long)(8)
# define KEY_V (unsigned long)(9)
# define KEY_B (unsigned long)(11)
# define KEY_N (unsigned long)(45)
# define KEY_M (unsigned long)(46)
# define KEY_LESS_THAN (unsigned long)(43)
# define KEY_COMMA (unsigned long)(43)
# define KEY_GREATER_THAN (unsigned long)(47)
# define KEY_DOT (unsigned long)(47)
# define KEY_SLASH (unsigned long)(44)
# define KEY_QUESTION_MARK (unsigned long)(44)
# define KEY_SHIFT_RIGHT (unsigned long)(258)
# define KEY_CTRL_LEFT (unsigned long)(256)
# define KEY_COMMAND_LEFT (unsigned long)(259)
# define KEY_OPTION_LEFT (unsigned long)(261)
# define KEY_ALT (unsigned long)(261)
# define KEY_SPACE (unsigned long)(0x20)
# define KEY_COMMAND_RIGHT (unsigned long)(260)
# define KEY_ALT_GR (unsigned long)(262)
# define KEY_FN (unsigned long)(279)
# define KEY_CTRL_RIGHT (unsigned long)(269)
# define KEY_LEFT (unsigned long)(0x445B1B)
# define KEY_DOWN (unsigned long)(0x425B1B)
# define KEY_RIGHT (unsigned long)(0x435B1B)
# define KEY_UP (unsigned long)(0x415B1B)
# define KEY_DEL (unsigned long)(117)
# define KEY_HOME (unsigned long)(0x485B1B)
# define KEY_END (unsigned long)(0x465B1B)
# define KEY_PAGE_UP (unsigned long)(116)
# define KEY_PAGE_DOWN (unsigned long)(121)
# define KEY_CLEAR (unsigned long)(71)
# define KEY_PAD_1 (unsigned long)(83)
# define KEY_PAD_2 (unsigned long)(84)
# define KEY_PAD_3 (unsigned long)(85)
# define KEY_PAD_4 (unsigned long)(86)
# define KEY_PAD_5 (unsigned long)(87)
# define KEY_PAD_6 (unsigned long)(88)
# define KEY_PAD_7 (unsigned long)(89)
# define KEY_PAD_8 (unsigned long)(91)
# define KEY_PAD_9 (unsigned long)(92)
# define KEY_PAD_0 (unsigned long)(82)
# define KEY_PAD_EQUAL (unsigned long)(81)
# define KEY_PAD_DIVIDE (unsigned long)(75)
# define KEY_PAD_MULTIPLY (unsigned long)(67)
# define KEY_PAD_SUB (unsigned long)(78)
# define KEY_PAD_ADD (unsigned long)(69)
# define KEY_PAD_ENTER (unsigned long)(76)
# define KEY_PAD_DOT (unsigned long)(65)
# define KEY_ALT_LEFT	0x435B1B1B
# define KEY_ALT_RIGHT	0x445B1B1B
# define KEY_ALT_UP		0x415B1B1B
# define KEY_ALT_DOWN	0x425B1B1B

#endif
